export const types = {
  FILL_POSTS: 'FILL_POSTS',
  CLEAR_POSTS: 'CLEAR_POSTS',
  CREATE_POST: 'CREATE_POST',
  LIKE_POST: 'LIKE_POST',
  UNLIKE_POST: 'UNLIKE_POST',

  FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
  CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
  DELETE_POST_ASYNC: 'DELETE_POST_ASYNC',
  LIKE_POST_ASYNC: 'LIKE_POST_ASYNC',
  UNLIKE_POST_ASYNC: 'UNLIKE_POST_ASYNC',
}