export const types = {
  FILL_POSTS: 'FILL_POSTS',
  CLEAR_POSTS: 'CLEAR_POSTS',

  FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
  CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
  DELETE_POST_ASYNC: 'DELETE_POST_ASYNC',
}